export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
        style={{backgroundColor:"greenyellow", padding:"50px"}}>
          Header
        </header>
        {children}
        <footer
        style={{backgroundColor:"blueviolet", padding:'50px'}}>
          Footer
        </footer>
      </body>
    </html>
  )
}
